### ISSUE TITLE
Add e2e test to existing flows

### ISSUE THREAD

**Issue by Tommytrg** [witnet/my-wit-wallet#353]
Add e2e test to cover the following flows:
- [x]  Create wallet flow
- [x]  Import from mnemonics
- [x]  Re-establish wallet
- [x]  Import an XPRV from Sheikah https://github.com/witnet/my-wit-wallet/pull/359
- [x]  Import an XPRV from myWitWallet https://github.com/witnet/my-wit-wallet/pull/359
- [x]  Import an XPRV from a node https://github.com/witnet/my-wit-wallet/pull/359
- [x]  Change the theme of the app
- [x]  Export an XPRV
- [ ]  Update wallet from wallet list
    - Show the wallet list
    - Change the selected wallet
    - Check if the transactions list is updated
    - Check if the balance is updated
    - Check if the selected address is updated
    - Check if the current wallet is loaded on logout and login
- [ ]  Show the address list
    - Change the address
    - Check the current address is updated
    - Generate a new address
    - Check the current address is the newly generated one
    - Check if the current address is selected when log-out and login again
- [ ]  Create transaction
    - Avoid sending a transaction if there is a connection error
    - Avoid sending a transaction if there is a validation error
    - Avoid sending a transaction if there is a miner fee validation error
    - Send a transaction with a weighted fee
    - Show pending transaction details
    - Reset transaction when changing wallet
